---
# Debian based OS
- name:  Debian | Add GPG key for rundeck repo
  apt_key:
    id: 6F167DC5EC83332F
    url: https://packages.rundeck.com/pagerduty/rundeck/gpgkey
  tags:
    - rundeck
    - install
    - packages

- name: Debian | Add Debian APT repository for rundeck
  apt_repository:
    repo: 'deb https://packages.rundeck.com/pagerduty/rundeck/any/ any main'
  tags:
    - rundeck
    - install
    - packages

- name: Debian | install from APT repository
  apt:
    name: "{{ rundeck_apt_package }}"
    state: present
  notify:
    - systemd daemon-reload
    - restart rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Debian | check upstart configuration exists
  register: upstart_config
  stat:
    path: /etc/init/rundeckd.conf
    get_md5: false
    get_checksum: false
  tags:
    - rundeck
    - install
    - packages

- name: Debian | remove System V init.d script if upstart config exists
  file:
    path: /etc/init.d/rundeckd
    state: absent
  when: upstart_config.stat.exists
  tags:
    - rundeck
    - install
    - packages

- name: set rundeck_package_command for debian
  set_fact:
    rundeck_package_command: dpkg -s
