---
# Debian based OS
- name:  Debian | Add GPG key for rundeck repo
  apt_key:
    id: 6F167DC5EC83332F
    url: https://packages.rundeck.com/pagerduty/rundeck/gpgkey
  tags:
    - rundeck
    - install
    - packages

- name: Debian | Add Debian APT repository for rundeck
  apt_repository:
    repo: 'deb https://packages.rundeck.com/pagerduty/rundeck/any/ any main'
  tags:
    - rundeck
    - install
    - packages

- name: Debian | install from APT repository
  apt:
    name: "{{ rundeck_apt_package }}"
    state: present
  notify:
    - systemd daemon-reload
    - restart rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Debian | check upstart configuration exists
  register: upstart_config
  stat:
    path: /etc/init/rundeckd.conf
    get_md5: false
    get_checksum: false
  tags:
    - rundeck
    - install
    - packages

- name: Debian | remove System V init.d script if upstart config exists
  file:
    path: /etc/init.d/rundeckd
    state: absent
  when: upstart_config.stat.exists
  tags:
    - rundeck
    - install
    - packages

- name: set rundeck_package_command for debian
  set_fact:
    rundeck_package_command: dpkg -s

- name: Debian | add systemd service helper
  copy:
    src: systemd/rundeck-start
    dest: /usr/bin/rundeck-start
    owner: root
    group: root
    mode: 0755
  when: ansible_service_mgr == 'systemd'
  tags:
    - rundeck
    - install
    - packages

- name: Debian | add systemd service unit
  copy:
    src: systemd/rundeckd.service
    dest: /etc/systemd/system/rundeckd.service
    owner: root
    group: root
    mode: 0644
  when: ansible_service_mgr == 'systemd'
  notify:
    - systemd daemon-reload
  tags:
    - rundeck
    - install
    - packages

- name: Debian | ensure service log directory has correct ownership
  file:
    path: /var/log/rundeck
    owner: rundeck
    state: directory
  tags:
    - rundeck
    - install
    - packages

- name: Debian | See if there are more log files
  find:
    paths: /var/log/rundeck
    file_type: file
    patterns: "*.log"
  register: rundeck_logfiles
  tags:
    - rundeck
    - install
    - packages
