---
# Instructions here: https://docs.rundeck.com/docs/administration/install/linux-deb.html
- name: Quick install
  get_url:
    url: https://raw.githubusercontent.com/rundeck/packaging/main/scripts/deb-setup.sh
    dest: /tmp/rundeck.sh
    mode: 0644

- name: Run script
  shell:
    cmd: cat /tmp/rundeck.sh | bash -s rundeck

- name: set rundeck_package_command for debian
  set_fact:
    rundeck_package_command: dpkg -s
